"""empty message

Revision ID: 0075cc06cb52
Revises: 5bc75186f94c
Create Date: 2022-05-24 18:06:54.356027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0075cc06cb52'
down_revision = '5bc75186f94c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotizacion', sa.Column('servicio_id', sa.Integer(), nullable=True))
    op.drop_constraint('cotizacion_ibfk_3', 'cotizacion', type_='foreignkey')
    op.create_foreign_key(None, 'cotizacion', 'servicio', ['servicio_id'], ['id'])
    op.drop_column('cotizacion', 'cotizacion_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotizacion', sa.Column('cotizacion_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cotizacion', type_='foreignkey')
    op.create_foreign_key('cotizacion_ibfk_3', 'cotizacion', 'servicio', ['cotizacion_id'], ['id'])
    op.drop_column('cotizacion', 'servicio_id')
    # ### end Alembic commands ###
