"""empty message

Revision ID: 069e911ba528
Revises: aca05a8c501f
Create Date: 2022-05-19 09:01:00.537373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069e911ba528'
down_revision = 'aca05a8c501f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('servicio_cliente', sa.Integer(), nullable=True))
    op.add_column('servicio', sa.Column('solicitud_servicio_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'servicio', 'solicitud', ['solicitud_servicio_id'], ['id'])
    op.create_foreign_key(None, 'servicio', 'clientes', ['servicio_cliente'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servicio', type_='foreignkey')
    op.drop_constraint(None, 'servicio', type_='foreignkey')
    op.drop_column('servicio', 'solicitud_servicio_id')
    op.drop_column('servicio', 'servicio_cliente')
    # ### end Alembic commands ###
