"""empty message

Revision ID: 14b5e29bc824
Revises: 0e8f6b8c25cf
Create Date: 2022-06-01 17:33:52.312464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14b5e29bc824'
down_revision = '0e8f6b8c25cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('servicio_ibfk_2', 'servicio', type_='foreignkey')
    op.drop_constraint('servicio_ibfk_1', 'servicio', type_='foreignkey')
    op.drop_column('servicio', 'solicitud_id')
    op.drop_column('servicio', 'cliente_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('cliente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('servicio', sa.Column('solicitud_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('servicio_ibfk_1', 'servicio', 'solicitud', ['solicitud_id'], ['id'])
    op.create_foreign_key('servicio_ibfk_2', 'servicio', 'clientes', ['cliente_id'], ['id'])
    # ### end Alembic commands ###
