"""empty message

Revision ID: 1e6baf3d13a3
Revises: 72a0bed8ae57
Create Date: 2022-04-27 16:31:13.583079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6baf3d13a3'
down_revision = '72a0bed8ae57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitud', sa.Column('servicio_campo', sa.String(length=120), nullable=False))
    op.add_column('solicitud', sa.Column('asesore', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitud', 'asesore')
    op.drop_column('solicitud', 'servicio_campo')
    # ### end Alembic commands ###
