"""empty message

Revision ID: 1f02d7b447e0
Revises: ba55a4a8f08f
Create Date: 2022-05-19 10:15:30.871030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f02d7b447e0'
down_revision = 'ba55a4a8f08f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitud', sa.Column('solicitud_servicio_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'solicitud', 'servicio', ['solicitud_servicio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solicitud', type_='foreignkey')
    op.drop_column('solicitud', 'solicitud_servicio_id')
    # ### end Alembic commands ###
