"""empty message

Revision ID: 26b19285f4e8
Revises: d669f2e9eb92
Create Date: 2022-05-25 17:22:20.700950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b19285f4e8'
down_revision = 'd669f2e9eb92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cotizacion_ibfk_3', 'cotizacion', type_='foreignkey')
    op.create_foreign_key(None, 'cotizacion', 'servicio', ['cotizacion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cotizacion', type_='foreignkey')
    op.create_foreign_key('cotizacion_ibfk_3', 'cotizacion', 'cotizacion', ['cotizacion_id'], ['id'])
    # ### end Alembic commands ###
