"""empty message

Revision ID: 2dd3c5eb158f
Revises: e889a2984456
Create Date: 2022-05-23 14:07:12.267924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2dd3c5eb158f'
down_revision = 'e889a2984456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('servicio_ibfk_1', 'servicio', type_='foreignkey')
    op.drop_column('servicio', 'cliente_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('cliente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('servicio_ibfk_1', 'servicio', 'clientes', ['cliente_id'], ['id'])
    # ### end Alembic commands ###
