"""empty message

Revision ID: 2ed78384e96a
Revises: 1f02d7b447e0
Create Date: 2022-05-19 10:26:12.919271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ed78384e96a'
down_revision = '1f02d7b447e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('servicio_ibfk_1', 'servicio', type_='foreignkey')
    op.drop_column('servicio', 'solicitud_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('solicitud_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('servicio_ibfk_1', 'servicio', 'solicitud', ['solicitud_id'], ['id'])
    # ### end Alembic commands ###
