"""empty message

Revision ID: 3b00b1a00ebc
Revises: bd12266dc6cf
Create Date: 2022-05-19 11:51:51.580532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b00b1a00ebc'
down_revision = 'bd12266dc6cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('servicio_ibfk_2', 'servicio', type_='foreignkey')
    op.drop_column('servicio', 'solicitud_id')
    op.add_column('solicitud', sa.Column('servicio_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'solicitud', 'servicio', ['servicio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solicitud', type_='foreignkey')
    op.drop_column('solicitud', 'servicio_id')
    op.add_column('servicio', sa.Column('solicitud_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('servicio_ibfk_2', 'servicio', 'solicitud', ['solicitud_id'], ['id'])
    # ### end Alembic commands ###
