"""empty message

Revision ID: 42879f394a60
Revises: db3217a26898
Create Date: 2022-04-27 21:37:38.661642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42879f394a60'
down_revision = 'db3217a26898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('solicitud_ibfk_1', 'solicitud', type_='foreignkey')
    op.create_foreign_key(None, 'solicitud', 'clientes', ['numero_solicitud'], ['id'])
    op.drop_column('solicitud', 'solicitud_cliente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitud', sa.Column('solicitud_cliente', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'solicitud', type_='foreignkey')
    op.create_foreign_key('solicitud_ibfk_1', 'solicitud', 'clientes', ['solicitud_cliente'], ['id'])
    # ### end Alembic commands ###
