"""empty message

Revision ID: 4a14ff8fcb7d
Revises: 177c13631573
Create Date: 2022-05-17 14:09:04.522549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a14ff8fcb7d'
down_revision = '177c13631573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('solicituds_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'servicio', 'solicitud', ['solicituds_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servicio', type_='foreignkey')
    op.drop_column('servicio', 'solicituds_id')
    # ### end Alembic commands ###
