"""empty message

Revision ID: 4af4b0f4e59b
Revises: fb0e54046cb2
Create Date: 2022-05-19 09:57:31.594893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4af4b0f4e59b'
down_revision = 'fb0e54046cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('solicitud_id', sa.Integer(), nullable=True))
    op.drop_constraint('servicio_ibfk_1', 'servicio', type_='foreignkey')
    op.create_foreign_key(None, 'servicio', 'solicitud', ['solicitud_id'], ['id'])
    op.drop_column('servicio', 'servicio_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('servicio_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'servicio', type_='foreignkey')
    op.create_foreign_key('servicio_ibfk_1', 'servicio', 'solicitud', ['servicio_id'], ['id'])
    op.drop_column('servicio', 'solicitud_id')
    # ### end Alembic commands ###
