"""empty message

Revision ID: 5b30645e7553
Revises: 522f2f77b26d
Create Date: 2022-06-01 17:12:58.831286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b30645e7553'
down_revision = '522f2f77b26d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('solicitud_id', sa.Integer(), nullable=True))
    op.drop_constraint('servicio_ibfk_1', 'servicio', type_='foreignkey')
    op.create_foreign_key(None, 'servicio', 'solicitud', ['solicitud_id'], ['id'])
    op.drop_column('servicio', 'cliente_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('cliente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'servicio', type_='foreignkey')
    op.create_foreign_key('servicio_ibfk_1', 'servicio', 'clientes', ['cliente_id'], ['id'])
    op.drop_column('servicio', 'solicitud_id')
    # ### end Alembic commands ###
