"""empty message

Revision ID: 5bc75186f94c
Revises: cf6ba0646d4a
Create Date: 2022-05-24 18:05:30.386747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5bc75186f94c'
down_revision = 'cf6ba0646d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotizacion', sa.Column('cotizacion_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cotizacion', 'servicio', ['cotizacion_id'], ['id'])
    op.drop_constraint('servicio_ibfk_3', 'servicio', type_='foreignkey')
    op.drop_column('servicio', 'cotizacion_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('cotizacion_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('servicio_ibfk_3', 'servicio', 'cotizacion', ['cotizacion_id'], ['id'])
    op.drop_constraint(None, 'cotizacion', type_='foreignkey')
    op.drop_column('cotizacion', 'cotizacion_id')
    # ### end Alembic commands ###
