"""empty message

Revision ID: 5d56682110f6
Revises: 7272cd93cc2b
Create Date: 2022-05-17 17:48:30.855340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d56682110f6'
down_revision = '7272cd93cc2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('servicio_ibfk_1', 'servicio', type_='foreignkey')
    op.drop_column('servicio', 'solicituds_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('solicituds_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('servicio_ibfk_1', 'servicio', 'solicitud', ['solicituds_id'], ['id'])
    # ### end Alembic commands ###
