"""empty message

Revision ID: 5d9bd94b1854
Revises: bc9ae0b7e502
Create Date: 2022-06-01 15:45:34.521259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d9bd94b1854'
down_revision = 'bc9ae0b7e502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('servicio_ibfk_2', 'servicio', type_='foreignkey')
    op.drop_column('servicio', 'solicitud_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('solicitud_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('servicio_ibfk_2', 'servicio', 'solicitud', ['solicitud_id'], ['id'])
    # ### end Alembic commands ###
