"""empty message

Revision ID: 645617b74c0a
Revises: ec4e1d603aad
Create Date: 2022-04-25 20:22:21.706676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '645617b74c0a'
down_revision = 'ec4e1d603aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'servicios')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('servicios', mysql.VARCHAR(collation='utf8_unicode_ci', length=120), nullable=False))
    # ### end Alembic commands ###
