"""empty message

Revision ID: 72a0bed8ae57
Revises: 645617b74c0a
Create Date: 2022-04-26 17:11:24.005625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72a0bed8ae57'
down_revision = '645617b74c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('solicitud_cliente', sa.Integer(), nullable=True))
    op.drop_constraint('clientes_ibfk_1', 'clientes', type_='foreignkey')
    op.create_foreign_key(None, 'clientes', 'solicitud', ['solicitud_cliente'], ['id'])
    op.drop_column('clientes', 'sol_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('sol_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.create_foreign_key('clientes_ibfk_1', 'clientes', 'solicitud', ['sol_id'], ['id'])
    op.drop_column('clientes', 'solicitud_cliente')
    # ### end Alembic commands ###
