"""empty message

Revision ID: 74e71d2c009b
Revises: 8b6ab8ea6bbf
Create Date: 2022-04-20 17:51:07.161767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e71d2c009b'
down_revision = '8b6ab8ea6bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asesor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primernombre_asesor', sa.String(length=120), nullable=False),
    sa.Column('apellido_asesor', sa.String(length=120), nullable=False),
    sa.Column('correo_asesor', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_servicio', sa.String(length=120), nullable=False),
    sa.Column('mensaje', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicio')
    op.drop_table('asesor')
    # ### end Alembic commands ###
