"""empty message

Revision ID: 75d8a7df0625
Revises: 8328cd73ab72
Create Date: 2022-06-01 14:27:17.230204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75d8a7df0625'
down_revision = '8328cd73ab72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('solicitud_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'servicio', 'solicitud', ['solicitud_id'], ['id'])
    op.drop_constraint('solicitud_ibfk_2', 'solicitud', type_='foreignkey')
    op.drop_column('solicitud', 'solicitud_servicio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitud', sa.Column('solicitud_servicio', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('solicitud_ibfk_2', 'solicitud', 'servicio', ['solicitud_servicio'], ['id'])
    op.drop_constraint(None, 'servicio', type_='foreignkey')
    op.drop_column('servicio', 'solicitud_id')
    # ### end Alembic commands ###
