"""empty message

Revision ID: 8328cd73ab72
Revises: 413c8a911269
Create Date: 2022-06-01 10:58:22.298504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8328cd73ab72'
down_revision = '413c8a911269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('servicio_ibfk_2', 'servicio', type_='foreignkey')
    op.drop_column('servicio', 'solicitudes_id')
    op.add_column('solicitud', sa.Column('solicitud_servicio', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'solicitud', 'servicio', ['solicitud_servicio'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solicitud', type_='foreignkey')
    op.drop_column('solicitud', 'solicitud_servicio')
    op.add_column('servicio', sa.Column('solicitudes_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('servicio_ibfk_2', 'servicio', 'solicitud', ['solicitudes_id'], ['id'])
    # ### end Alembic commands ###
