"""empty message

Revision ID: 8fb728eea22e
Revises: 5d56682110f6
Create Date: 2022-05-19 07:52:34.098887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8fb728eea22e'
down_revision = '5d56682110f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('sorvic', sa.Integer(), nullable=True))
    op.drop_constraint('servicio_ibfk_2', 'servicio', type_='foreignkey')
    op.create_foreign_key(None, 'servicio', 'solicitud', ['sorvic'], ['id'])
    op.drop_column('servicio', 'clonts_id')
    op.drop_constraint('solicitud_ibfk_2', 'solicitud', type_='foreignkey')
    op.drop_column('solicitud', 'sorvic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitud', sa.Column('sorvic', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('solicitud_ibfk_2', 'solicitud', 'servicio', ['sorvic'], ['id'])
    op.add_column('servicio', sa.Column('clonts_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'servicio', type_='foreignkey')
    op.create_foreign_key('servicio_ibfk_2', 'servicio', 'clientes', ['clonts_id'], ['id'])
    op.drop_column('servicio', 'sorvic')
    # ### end Alembic commands ###
