"""empty message

Revision ID: 937a80b723b3
Revises: 2810b159c7dd
Create Date: 2022-06-02 11:30:56.322256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '937a80b723b3'
down_revision = '2810b159c7dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotizacion', sa.Column('costo_servicio', sa.Integer(), nullable=False))
    op.drop_column('solicitud', 'costo_servicio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitud', sa.Column('costo_servicio', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('cotizacion', 'costo_servicio')
    # ### end Alembic commands ###
