"""empty message

Revision ID: abde0b0c2840
Revises: 2ed78384e96a
Create Date: 2022-05-19 10:54:06.988960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'abde0b0c2840'
down_revision = '2ed78384e96a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('solicitud_ibfk_2', 'solicitud', type_='foreignkey')
    op.drop_column('solicitud', 'solicitud_servicio_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitud', sa.Column('solicitud_servicio_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('solicitud_ibfk_2', 'solicitud', 'servicio', ['solicitud_servicio_id'], ['id'])
    # ### end Alembic commands ###
