"""empty message

Revision ID: aca05a8c501f
Revises: 8fb728eea22e
Create Date: 2022-05-19 08:03:50.467898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aca05a8c501f'
down_revision = '8fb728eea22e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('servicio_ibfk_1', 'servicio', type_='foreignkey')
    op.drop_column('servicio', 'sorvic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('sorvic', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('servicio_ibfk_1', 'servicio', 'solicitud', ['sorvic'], ['id'])
    # ### end Alembic commands ###
