"""empty message

Revision ID: bc9ae0b7e502
Revises: 10df63eb8fdb
Create Date: 2022-06-01 15:43:06.754820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc9ae0b7e502'
down_revision = '10df63eb8fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitud', sa.Column('servicios_cliente', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'solicitud', 'servicio', ['servicios_cliente'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solicitud', type_='foreignkey')
    op.drop_column('solicitud', 'servicios_cliente')
    # ### end Alembic commands ###
