"""empty message

Revision ID: bd12266dc6cf
Revises: d601ce9a9590
Create Date: 2022-05-19 11:44:18.114220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd12266dc6cf'
down_revision = 'd601ce9a9590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('solicitud_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'servicio', 'solicitud', ['solicitud_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servicio', type_='foreignkey')
    op.drop_column('servicio', 'solicitud_id')
    # ### end Alembic commands ###
