"""empty message

Revision ID: c202e2abb3d8
Revises: 5b30645e7553
Create Date: 2022-06-01 17:19:45.428003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c202e2abb3d8'
down_revision = '5b30645e7553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'servicio', 'clientes', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servicio', type_='foreignkey')
    op.drop_column('servicio', 'cliente_id')
    # ### end Alembic commands ###
