"""empty message

Revision ID: c6a3e329887a
Revises: 
Create Date: 2022-04-19 13:21:28.724580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6a3e329887a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicio')
    op.drop_table('asesor')
    op.drop_table('estadocliente')
    op.create_foreign_key(None, 'cotizacion', 'clientes', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cotizacion', type_='foreignkey')
    op.create_table('estadocliente',
    sa.Column('id_estado', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre_estado', mysql.VARCHAR(collation='utf8_unicode_ci', length=80), nullable=False),
    sa.PrimaryKeyConstraint('id_estado'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('asesor',
    sa.Column('id_asesor', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombres', mysql.VARCHAR(collation='utf8_unicode_ci', length=80), nullable=False),
    sa.Column('apellidos', mysql.VARCHAR(collation='utf8_unicode_ci', length=80), nullable=False),
    sa.Column('correo', mysql.VARCHAR(collation='utf8_unicode_ci', length=120), nullable=False),
    sa.Column('dirección', mysql.VARCHAR(collation='utf8_unicode_ci', length=120), nullable=False),
    sa.Column('celular', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_asesor'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('servicio',
    sa.Column('id_servicio', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre_servicio', mysql.VARCHAR(collation='utf8_unicode_ci', length=120), nullable=False),
    sa.PrimaryKeyConstraint('id_servicio'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
