"""empty message

Revision ID: ccb47d225d3b
Revises: 7ea01639363e
Create Date: 2022-06-01 10:37:54.040693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ccb47d225d3b'
down_revision = '7ea01639363e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotizacion', sa.Column('servicio_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cotizacion', 'servicio', ['servicio_id'], ['id'])
    op.drop_constraint('servicio_ibfk_3', 'servicio', type_='foreignkey')
    op.drop_column('servicio', 'cotizacion_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('cotizacion_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('servicio_ibfk_3', 'servicio', 'cotizacion', ['cotizacion_id'], ['id'])
    op.drop_constraint(None, 'cotizacion', type_='foreignkey')
    op.drop_column('cotizacion', 'servicio_id')
    # ### end Alembic commands ###
