"""empty message

Revision ID: cea25ac970cb
Revises: 937a80b723b3
Create Date: 2022-06-02 17:51:32.051459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea25ac970cb'
down_revision = '937a80b723b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicio_campo', sa.String(length=120), nullable=False),
    sa.Column('asesore', sa.String(length=120), nullable=False),
    sa.Column('solicitud_cliente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['solicitud_cliente'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cotizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('costo_servicio', sa.Integer(), nullable=False),
    sa.Column('numero_horas', sa.Integer(), nullable=False),
    sa.Column('descuento', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('solicitud_id', sa.Integer(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cotizacion')
    op.drop_table('solicitud')
    # ### end Alembic commands ###
