"""empty message

Revision ID: cf6ba0646d4a
Revises: 6a92e02013ec
Create Date: 2022-05-24 17:53:49.322080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6ba0646d4a'
down_revision = '6a92e02013ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('cotizacion_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'servicio', 'cotizacion', ['cotizacion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servicio', type_='foreignkey')
    op.drop_column('servicio', 'cotizacion_id')
    # ### end Alembic commands ###
