"""empty message

Revision ID: d669f2e9eb92
Revises: 292bf16bc6e4
Create Date: 2022-05-25 17:20:51.531247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd669f2e9eb92'
down_revision = '292bf16bc6e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotizacion', sa.Column('cotizacion_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cotizacion', 'cotizacion', ['cotizacion_id'], ['id'])
    op.drop_constraint('servicio_ibfk_3', 'servicio', type_='foreignkey')
    op.drop_column('servicio', 'cotizacion_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('cotizacion_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('servicio_ibfk_3', 'servicio', 'cotizacion', ['cotizacion_id'], ['id'])
    op.drop_constraint(None, 'cotizacion', type_='foreignkey')
    op.drop_column('cotizacion', 'cotizacion_id')
    # ### end Alembic commands ###
