"""empty message

Revision ID: dbb5019fc5ba
Revises: 74e71d2c009b
Create Date: 2022-04-21 17:40:53.438489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbb5019fc5ba'
down_revision = '74e71d2c009b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicio', 'mensaje')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('mensaje', mysql.VARCHAR(collation='utf8_unicode_ci', length=500), nullable=False))
    # ### end Alembic commands ###
