"""empty message

Revision ID: e889a2984456
Revises: 8fc94e312408
Create Date: 2022-05-19 14:29:08.005826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e889a2984456'
down_revision = '8fc94e312408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('solicitud_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'servicio', 'solicitud', ['solicitud_id'], ['id'])
    op.drop_constraint('solicitud_ibfk_1', 'solicitud', type_='foreignkey')
    op.drop_column('solicitud', 'servicio_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitud', sa.Column('servicio_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('solicitud_ibfk_1', 'solicitud', 'servicio', ['servicio_id'], ['id'])
    op.drop_constraint(None, 'servicio', type_='foreignkey')
    op.drop_column('servicio', 'solicitud_id')
    # ### end Alembic commands ###
