"""empty message

Revision ID: ec4e1d603aad
Revises: dbb5019fc5ba
Create Date: 2022-04-25 20:01:09.191482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4e1d603aad'
down_revision = 'dbb5019fc5ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_solicitud', sa.Integer(), autoincrement=True, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('asesor', sa.Column('soli_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'asesor', 'solicitud', ['soli_id'], ['id'])
    op.add_column('clientes', sa.Column('sol_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clientes', 'solicitud', ['sol_id'], ['id'])
    op.add_column('servicio', sa.Column('costo_servicio', sa.Integer(), nullable=False))
    op.add_column('servicio', sa.Column('solicitud_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'servicio', 'solicitud', ['solicitud_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servicio', type_='foreignkey')
    op.drop_column('servicio', 'solicitud_id')
    op.drop_column('servicio', 'costo_servicio')
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_column('clientes', 'sol_id')
    op.drop_constraint(None, 'asesor', type_='foreignkey')
    op.drop_column('asesor', 'soli_id')
    op.drop_table('solicitud')
    # ### end Alembic commands ###
