"""empty message

Revision ID: fa0a8006c6c1
Revises: 4a14ff8fcb7d
Create Date: 2022-05-17 17:36:00.560897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa0a8006c6c1'
down_revision = '4a14ff8fcb7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('clonts_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'servicio', 'clientes', ['clonts_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servicio', type_='foreignkey')
    op.drop_column('servicio', 'clonts_id')
    # ### end Alembic commands ###
